name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Copy files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "./"
        target: "/var/www/straders.ru"
    
    - name: Run deploy commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/straders.ru
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          sudo systemctl restart nginx
